services:
  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - main
    restart: unless-stopped

  scrapper:  
    image: mitugui/inovamar:scrapper
    container_name: scrapper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/calls"]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      selenium:
        condition: service_healthy
    networks:
      - main
    restart: unless-stopped

  frontend:
    image: mitugui/inovamar:frontend
    container_name: frontend
    ports:
      - "127.0.0.1:8073:80"
    depends_on:
      scrapper:
        condition: service_healthy
    networks:
      - main
    restart: unless-stopped

networks:
  main: