services:
  selenium:
    image: selenium/standalone-firefox:latest
    container_name: selenium
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - main

  scrapper:  
    build:
      context: ./public_calls_scrapping/src
    container_name: scrapper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/calls"]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      selenium:
        condition: service_healthy
    networks:
      - main

  frontend:
    build:
      context: ./escritorio-de-projetos
    container_name: frontend
    ports:
      - "127.0.0.1:8073:80"
    depends_on:
      scrapper:
        condition: service_healthy
    networks:
      - main

networks:
  main: